"""
Nifty 50 constituent tickers as of April 2026.
yfinance format: append .NS for NSE, .BO for BSE.
"""

NIFTY50_TICKERS: dict[str, str] = {
    "ADANIENT": "Adani Enterprises",
    "ADANIPORTS": "Adani Ports & SEZ",
    "APOLLOHOSP": "Apollo Hospitals",
    "ASIANPAINT": "Asian Paints",
    "AXISBANK": "Axis Bank",
    "BAJAJ-AUTO": "Bajaj Auto",
    "BAJFINANCE": "Bajaj Finance",
    "BAJAJFINSV": "Bajaj Finserv",
    "BEL": "Bharat Electronics",
    "BPCL": "BPCL",
    "BHARTIARTL": "Bharti Airtel",
    "BRITANNIA": "Britannia Industries",
    "CIPLA": "Cipla",
    "COALINDIA": "Coal India",
    "DRREDDY": "Dr Reddy's Laboratories",
    "EICHERMOT": "Eicher Motors",
    "GRASIM": "Grasim Industries",
    "HCLTECH": "HCL Technologies",
    "HDFCBANK": "HDFC Bank",
    "HDFCLIFE": "HDFC Life Insurance",
    "HEROMOTOCO": "Hero MotoCorp",
    "HINDALCO": "Hindalco Industries",
    "HINDUNILVR": "Hindustan Unilever",
    "ICICIBANK": "ICICI Bank",
    "ITC": "ITC",
    "INDUSINDBK": "IndusInd Bank",
    "INFY": "Infosys",
    "JSWSTEEL": "JSW Steel",
    "KOTAKBANK": "Kotak Mahindra Bank",
    "LT": "Larsen & Toubro",
    "M&M": "Mahindra & Mahindra",
    "MARUTI": "Maruti Suzuki India",
    "NTPC": "NTPC",
    "NESTLEIND": "Nestle India",
    "ONGC": "Oil & Natural Gas Corporation",
    "POWERGRID": "Power Grid Corporation",
    "RELIANCE": "Reliance Industries",
    "SBILIFE": "SBI Life Insurance",
    "SHRIRAMFIN": "Shriram Finance",
    "SBIN": "State Bank of India",
    "SUNPHARMA": "Sun Pharmaceutical Industries",
    "TCS": "Tata Consultancy Services",
    "TATACONSUM": "Tata Consumer Products",
    "TATAMOTORS": "Tata Motors",
    "TATASTEEL": "Tata Steel",
    "TECHM": "Tech Mahindra",
    "TITAN": "Titan Company",
    "ULTRACEMCO": "UltraTech Cement",
    "WIPRO": "Wipro",
    "ZOMATO": "Zomato",
}

# yfinance-ready tickers (append .NS)
NIFTY50_YF_TICKERS: list[str] = [f"{t}.NS" for t in NIFTY50_TICKERS]
