"""
Research Orchestrator — the brain of the system.

Coordinates all agents to produce a complete research report:
  Step 1: FundamentalAgent  → financial health analysis
  Step 2: SentimentAgent    → news + transcript sentiment
  Step 3: ScenarioAgent     → bull/base/bear with price targets
  Step 4: ConvictionAgent   → plain-English summary

Usage (CLI):
    python -m src.agents.orchestrator --ticker RELIANCE.NS

Usage (Python):
    orch = ResearchOrchestrator()
    report = orch.research("RELIANCE.NS")
    print(report.to_markdown())
"""

import argparse
import json
import os
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

from src.agents.fundamental_agent import FundamentalAgent
from src.agents.sentiment_agent import SentimentAgent
from src.agents.scenario_agent import ScenarioAgent
from src.agents.conviction_agent import ConvictionAgent
from src.llm import get_llm_client
from src.rag.retriever import Retriever
from config.nifty50_tickers import NIFTY50_TICKERS
from config.settings import get_settings
from src.utils.logger import get_logger
from src.utils.helpers import ensure_dir

logger = get_logger(__name__)
settings = get_settings()


@dataclass
class ResearchReport:
    ticker: str
    company_name: str
    generated_at: str
    fundamental_analysis: str = ""
    sentiment_analysis: str = ""
    scenario_analysis: str = ""
    conviction_summary: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_markdown(self) -> str:
        divider = "\n\n---\n\n"
        return f"""# EquityLens Research Report
**Company:** {self.company_name} ({self.ticker})
**Generated:** {self.generated_at}

---

# PART I — FUNDAMENTAL ANALYSIS

{self.fundamental_analysis}

{divider}

# PART II — SENTIMENT & NEWS ANALYSIS

{self.sentiment_analysis}

{divider}

# PART III — SCENARIO ANALYSIS (BULL / BASE / BEAR)

{self.scenario_analysis}

{divider}

# PART IV — CONVICTION SUMMARY (FOR RETAIL INVESTORS)

{self.conviction_summary}

---
*Generated by EquityLens AI | For educational purposes only | Not SEBI-registered investment advice*
"""

    def to_dict(self) -> dict[str, Any]:
        return {
            "ticker": self.ticker,
            "company_name": self.company_name,
            "generated_at": self.generated_at,
            "fundamental_analysis": self.fundamental_analysis,
            "sentiment_analysis": self.sentiment_analysis,
            "scenario_analysis": self.scenario_analysis,
            "conviction_summary": self.conviction_summary,
            "metadata": self.metadata,
        }

    def save(self, output_dir: str = "reports") -> str:
        ensure_dir(output_dir)
        clean = self.ticker.replace(".", "_")
        ts = datetime.utcnow().strftime("%Y%m%d_%H%M")

        md_path = os.path.join(output_dir, f"{clean}_{ts}.md")
        json_path = os.path.join(output_dir, f"{clean}_{ts}.json")

        with open(md_path, "w") as f:
            f.write(self.to_markdown())
        with open(json_path, "w") as f:
            json.dump(self.to_dict(), f, indent=2)

        logger.info(f"Report saved → {md_path}")
        return md_path


class ResearchOrchestrator:

    def __init__(self) -> None:
        self.retriever = Retriever()
        self.llm = get_llm_client()

        self.fundamental_agent = FundamentalAgent(retriever=self.retriever, llm=self.llm)
        self.sentiment_agent = SentimentAgent(retriever=self.retriever, llm=self.llm)
        self.scenario_agent = ScenarioAgent(retriever=self.retriever, llm=self.llm)
        self.conviction_agent = ConvictionAgent(llm=self.llm)

    def research(
        self,
        ticker_yf: str,
        horizon: str = "3 years",
        question: str = "",
        save: bool = True,
    ) -> ResearchReport:
        """
        Run the full research pipeline for a ticker.

        Args:
            ticker_yf:  e.g. 'RELIANCE.NS'
            horizon:    Scenario horizon ('1 year', '3 years', '5 years')
            question:   Optional specific question to answer in the analysis
            save:       Whether to save the report to disk

        Returns:
            ResearchReport dataclass with all four analysis sections
        """
        nse_symbol = ticker_yf.replace(".NS", "").replace(".BO", "")
        company_name = NIFTY50_TICKERS.get(nse_symbol, nse_symbol)

        logger.info(f"{'='*60}")
        logger.info(f"Research Report: {company_name} ({ticker_yf})")
        logger.info(f"{'='*60}")

        report = ResearchReport(
            ticker=ticker_yf,
            company_name=company_name,
            generated_at=datetime.utcnow().isoformat(),
        )

        # Step 1: Fundamental analysis
        logger.info("[1/4] Running Fundamental Analysis...")
        report.fundamental_analysis = self.fundamental_agent.run(
            ticker=ticker_yf,
            company_name=company_name,
            question=question,
        )

        # Step 2: Sentiment analysis
        logger.info("[2/4] Running Sentiment Analysis...")
        report.sentiment_analysis = self.sentiment_agent.run(
            ticker=ticker_yf,
            company_name=company_name,
        )

        # Step 3: Scenario building (informed by fundamentals)
        logger.info("[3/4] Building Investment Scenarios...")
        report.scenario_analysis = self.scenario_agent.run(
            ticker=ticker_yf,
            company_name=company_name,
            horizon=horizon,
            fundamental_context=report.fundamental_analysis[:2000],
        )

        # Step 4: Conviction summary for retail investors
        logger.info("[4/4] Writing Conviction Summary...")
        report.conviction_summary = self.conviction_agent.run(
            ticker=ticker_yf,
            company_name=company_name,
            fundamental_analysis=report.fundamental_analysis,
            scenario_analysis=report.scenario_analysis,
        )

        logger.info("Research complete.")

        if save:
            path = report.save()
            report.metadata["saved_to"] = path

        return report

    def quick_answer(self, ticker_yf: str, question: str) -> str:
        """
        Lightweight single-question Q&A without full multi-agent pipeline.
        Useful for quick lookups: "What is Reliance's debt-to-equity?"
        """
        nse_symbol = ticker_yf.replace(".NS", "").replace(".BO", "")
        company_name = NIFTY50_TICKERS.get(nse_symbol, nse_symbol)

        results = self.retriever.retrieve(question, ticker=ticker_yf, top_k=6)
        context = self.retriever.format_context(results)

        system = (
            "You are a concise financial analyst. Answer the question directly using "
            "the provided data. Be specific and cite numbers. Max 200 words."
        )
        return self.llm.complete(
            system_prompt=system,
            user_message=f"Question about {company_name} ({ticker_yf}): {question}",
            context=context,
            temperature=0.1,
        )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="EquityLens — AI Equity Research")
    parser.add_argument("--ticker", type=str, required=True, help="e.g. RELIANCE.NS")
    parser.add_argument("--horizon", type=str, default="3 years")
    parser.add_argument("--question", type=str, default="", help="Specific question")
    parser.add_argument("--quick", action="store_true", help="Quick Q&A mode")
    args = parser.parse_args()

    orch = ResearchOrchestrator()

    if args.quick:
        if not args.question:
            print("--quick mode requires --question")
        else:
            answer = orch.quick_answer(args.ticker, args.question)
            print(f"\n{answer}")
    else:
        report = orch.research(args.ticker, horizon=args.horizon, question=args.question)
        print("\n" + "="*60)
        print(report.to_markdown())
